---
- name: Trust RVM's developer GPG key
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- name: Install RVM on single user mode
  shell: curl -sSL https://get.rvm.io | bash -sl stable
- name: Set rvmrc
  copy: src=.rvmrc dest=~/.rvmrc
