---
- hosts: local
  connection: local
  vars:
    notebook: true
    wifi_toggle_workaround: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  roles:
    - common
    - intel-ucode
    - intel-graphics
    - xorg
    - awesomewm
    - lightdm
    - acpid
    - laptop-mode-tools
    - ufw
    - zsh
