---
- hosts: localhost
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  roles:
    - common
    - intel-ucode
    - intel-graphics
    - awesomewm
    - lightdm