---
- name: Install xorg-server package
  pacman: name=xorg-server state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install libinput
  pacman: name=xf86-input-libinput state=present
  become: yes
  become_user: root
  become_method: sudo
