---
- name: Install xf86-video-intel
  pacman: name=xf86-video-intel state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install mesa
  pacman: name=mesa state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install lib32-mesa
  pacman: name=lib32-mesa state=present
  become: yes
  become_user: root
  become_method: sudo
