---
- file: dest=~/.config/awesome state=directory
- template: src=rc/main.lua.j2 dest=~/.config/awesome/rc.lua
- name: Install ArchLinux Wallpapers
  pacman: name=archlinux-wallpaper state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Set AwesomeWM theme
  copy: src=theme dest=~/.config/awesome
