---
- name: Install rxvt-unicode package
  pacman: name=rxvt-unicode state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Configure through Xresources
  copy: src=.Xresources dest=~/.Xresources
