---
- name: Install vicious package
  pacman: name=vicious state=present
- name: Install alsa-utils package
  pacman: name=alsa-utils state=present
- name: Install curl package
  pacman: name=curl state=present
- name: Install hddtemp package
  pacman: name=hddtemp state=present
- name: Install wireless_tools package
  pacman: name=wireless_tools state=present
