---
- name: Install gdal package # equired by VTK's Python 2 binding
  pacman: name=gdal state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install openmpi package # equired by VTK's Python 2 binding
  pacman: name=openmpi state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install unixodbc package # equired by VTK's Python 2 binding
  pacman: name=unixodbc state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install qt package # equired by VTK's Python 2 binding
  pacman: name=qt state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install vtk package
  pacman: name=vtk state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install boost package
  pacman: name=boost state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install armadillo package
  pacaur: name=armadillo state=present force=yes
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install lcov package
  pacaur: name=lcov state=present force=yes
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
