---
- name: Install openssl
  pacman: name=openssl state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install openssh
  pacman: name=openssh state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Set SSH private key files
  include_tasks: set_key.yml
- name: Set SSH config
  copy: src=config dest=~/.ssh/config
