---
- name: Disable systemd power management (logind)
  include: disable_logind.yml
- name: Install ACPID
  include: install.yml
- name: Setup wifi toggle
  include: wifi_toggle.yml
  when: notebook is defined
