---
- name: Disable systemd power management (logind)
  include_tasks: disable_logind.yml
- name: Install ACPID
  include_tasks: install.yml
- name: Setup wifi toggle
  include_tasks: wifi_toggle.yml
  when: notebook is defined
