---
- name: Install ufw
  include: install.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Configure ufw
  include: configure.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Block all traffic
  include: close.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Set incoming traffic exceptions
  include: incoming_allowed.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Enable ufw
  ufw: state=enabled policy=deny
  become: yes
  become_user: root
  become_method: sudo
