---
- name: Set pacman preferences
  template: src=pacman.conf dest=/etc/pacman.conf
  become: yes
  become_user: root
  become_method: sudo
- name: Update mirrorlist
  include: mirrorlist.yml
  become: yes
  become_user: root
  become_method: sudo
