---
- name: Install cups package
  pacman: name=cups state=present
- name: Install ghostscript package
  pacman: name=ghostscript state=present
- name: Install gsfonts package
  pacman: name=gsfonts state=present
- name: Install gutenprint package
  pacman: name=gutenprint state=present
- name: Install foomatic-db-gutenprint package
  pacman: name=foomatic-db-gutenprint state=present
- name: Install foomatic-db-gutenprint-ppds package
  pacman: name=foomatic-db-gutenprint-ppds state=present
