---
- name: Set the SUDOers file
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'
  become: yes
  become_user: root
  become_method: sudo
- name: Set system locales
  include: locale.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Configure pacman
  include: configure_pacman.yml
- name: Update the system
  pacman: update_cache=yes upgrade=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Check cower installed
  command: pacman -Q cower
  register: cower_installed
  ignore_errors: True
  changed_when: False
  check_mode: no
- name: Check pacaur installed
  command: pacman -Q pacaur
  register: pacaur_installed
  ignore_errors: True
  changed_when: False
  check_mode: no
- name: Install base-devel
  include: base-devel.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Install cower
  include: cower.yml
  when: cower_installed|failed
- name: Install pacaur
  include: pacaur.yml
  when: pacaur_installed|failed
- name: Update AUR packages
  pacaur: update_cache=yes upgrade=yes
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install vim
  include: vim.yml
- name: Install git
  include: git.yml
- name: Install htop
  pacman: name=htop state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install NetworkManager
  include: networkmanager.yml
- name: Create Pandora's Box directory
  include: pandorasbox.yml
- name: Install alsa-utils
  pacman: name=alsa-utils state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Setup web browsers
  include: browsers.yml
- name: Set timezone
  file: src=/usr/share/zoneinfo/Brazil/East dest=/etc/localtime state=link force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Setup systemd-timesyncd
  include: systemd-timesyncd.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Setup vlc
  include: vlc.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Setup CUPS
  include: cups.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Install ttf-dejavu package # (high quality, general-purpose fonts with good Unicode coverage)
  pacman: name=ttf-dejavu state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install xclip package
  pacman: name=xclip state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install wget package
  pacman: name=wget state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install evince package
  pacman: name=evince state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install skype package
  pacaur: name=skypeforlinux-bin state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install gimp package
  pacman: name=gimp state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install inkscape package
  pacman: name=inkscape state=present
  become: yes
  become_user: root
  become_method: sudo
