---
- name: Update mirrorlist
  include: mirrorlist.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Check cower installed
  command: pacman -Q cower
  register: cower_installed
  ignore_errors: True
  changed_when: False
  always_run: yes
- name: Check pacaur installed
  command: pacman -Q pacaur
  register: pacaur_installed
  ignore_errors: True
  changed_when: False
  always_run: yes
- name: Install base-devel
  include: base-devel.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Install cower
  include: cower.yml
  when: cower_installed|failed
- name: Install pacaur
  include: pacaur.yml
  when: pacaur_installed|failed
