- name: Install NetworkManager package
  pacman: name=networkmanager state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Start NetworkManager services
  service: name=NetworkManager enabled=yes state=started
  become: yes
  become_user: root
  become_method: sudo
- service: name=NetworkManager-dispatcher enabled=yes state=started
  become: yes
  become_user: root
  become_method: sudo
  changed_when: False # It does not behaviour well when reporting its status to systemd
