---
- file: dest=/tmp/pacaur state=directory
- name: Download pacaur PKGBUILG
  get_url: url=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur dest=/tmp/pacaur/PKGBUILD
- name: Build and install pacaur
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/pacaur
