---
- name: Create SSH configurations folder
  file: path=~/.ssh state=directory
- name: Load SSH key
  include_vars: private_key.yml
  no_log: true
- name: Create SSH key files
  copy:
    dest="{{ item.key }}"
    content="{{ item.value.content }}"
    mode=600
  with_dict: "{{ private_key }}"
  no_log: true
