---
- name: Setup CPU scaling
  include: cpu_scaling.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Install laptop-mode-tools-git
  # Git version preferred over the mainstream beacuse of sustemd incompatibility:
  # * https://bbs.archlinux.org/viewtopic.php?id=209100
  pacaur: name=laptop-mode-tools-git state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
